### ISSUE TITLE
Bosses

### ISSUE THREAD

**Issue by Dankco** [SRS-Scarab/Scarab#28]
1. Miniboss- based on something tentative (Act I boss)
2. Caravaneer boss- based on Chiron in the bazaar (Act II boss)
3. Cerebus boss- guards the gates to hell (Act III boss)
4. Final boss- boss at the end of the game (tentative)

**Comment by Phantom-101** [comment]
closing for now since we have one for the demo, will create individual issues for any new bosses we need
